development:
  adapter: postgresql
  encoding: unicode
  database: boikeno_database
  pool: 5
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: boikeno_database
  pool: 5
  host: localhost
  username: postgres
  password: postgres